/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.eugenesy.scapegoat.example.app;

object AppService {
    def getGreeting() {
        return "Hello world.";
    }
}

object Test {
    val a = "input"
    println(if (a.length > 3) {
        "long string"
    } else {
        "long string"
    })
}

object Test2 {
    val a = "input"
    val len = a.length
    if (1 > 0) {
        val len = a.length
        println(s"Length is $len")
    } else {
        val len = a.length
        println("I won't say")
    }
}