/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/tutorial_java_projects.html
 */

plugins {
    java
    application
    scala
}

repositories {
    jcenter()
}

//val scalaCompilerPlugin by configurations.creating

dependencies {
    implementation("org.scala-lang:scala-library:2.12.10")
//    scalaCompilerPlugin("com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3")
}

application {
    // Define the main class for the application.
    mainClassName = "com.github.eugenesy.scapegoat.example.app.App"
}


buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath("com.github.eugenesy.scapegoat:gradle-scapegoat-plugin:1.0")
    }
}
apply(plugin = "com.github.eugenesy.scapegoat")

configure<com.github.eugenesy.scapegoat.ScapegoatExtension>  {
    reports = arrayListOf("html")
}
